# config.nu - interactive configuration, loaded after env.nu.

$env.config.edit_mode = "vi"
$env.config.show_banner = false

source aliases.nu

# zoxide/starship init scripts, generated by nushell/install.sh (same pattern
# as ~/.fzf.zsh). Must be top-level sources: defs from a file sourced inside a
# block stay scoped to that block. If a file is missing, re-run the installer.
source ~/.zoxide.nu
source ~/.starship.nu
